SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE access_permission;
TRUNCATE TABLE archives;
TRUNCATE TABLE archives_bound_folder;
TRUNCATE TABLE archives_file;
TRUNCATE TABLE archives_folder;
TRUNCATE TABLE archives_inherit;
TRUNCATE TABLE data_pemission_common;
TRUNCATE TABLE data_pemission_share;
TRUNCATE TABLE file;
TRUNCATE TABLE flow;
TRUNCATE TABLE flow_node;
TRUNCATE TABLE flow_node_audit_option;
TRUNCATE TABLE flow_node_condition_option;
TRUNCATE TABLE flow_node_person_option;
TRUNCATE TABLE flow_run;
TRUNCATE TABLE flow_run_audit_detail;
TRUNCATE TABLE flow_run_cc_detail;
TRUNCATE TABLE flow_run_progress;
TRUNCATE TABLE migrations;
TRUNCATE TABLE organization;
TRUNCATE TABLE projects;
TRUNCATE TABLE research;
TRUNCATE TABLE resources_flow_run;
TRUNCATE TABLE resources_organization_flow;
TRUNCATE TABLE role;
TRUNCATE TABLE users_extends;
TRUNCATE TABLE users_organization;
TRUNCATE TABLE users_role;
TRUNCATE TABLE users_token;
TRUNCATE TABLE users;
SET GLOBAL FOREIGN_KEY_CHECKS = 1;
INSERT INTO `users` (`id`,`username`,`account`,`password`,`gender`,`email`,`mobile`,`remain`,`status`,`working_status`,`create_time`) 
VALUES(1,'超级管理员','lhsoft','$2y$10$RDNuJafPVBOz1cPoPxeo5.T4M5o2RC3EGKU5/eY4zSQs8gR19E5Da',1,'','15888888888',5,1,1,'2020-04-27');